### ISSUE TITLE
int/float conversion

### ISSUE THREAD

**Issue by xgodon** [guillon/xmlplain#1]
how can i make the lib convert strings into int or floats?

something like :
```
def postprocessor(path, key, value):
            try:
                return key + ':int', int(value)
            except (ValueError, TypeError):
return key, value
```

**Comment by guillon** [comment]
Did you try to use the process_content function parameter in the
xmlplain.xml_to_obj(inf, encoding='UTF-8', strip_space=False, fold_dict=False, process_content=None)
call? Ref to the doc at: https://guillon.github.io/xmlplain/
I'm not sure it will work, as it may be enforced at some points that values are strings.

**Comment by xgodon** [comment]
oh ! ok  i thought it was only for CDATA section.
thanks

**Comment by guillon** [comment]
Yes, cdata meaning there, in the doc, content data after parsing (escaped CDATA or not).

But, as I said, i'm not sure it will be sufficient as the original intent of this process_content is for string to string filter (w/o changing the type).

If you manage to use it for your purpose, please give an example that I will add to the regression tests.

**Comment by xgodon** [comment]
of course ! 

```
import xmlplain


def postprocessor(value):
    try:
        return int(value)
    except (ValueError, TypeError):
        return value

f = """<example>
        <str>baguette</str>
        <int>1</int>
      </example>"""

my_dict = xmlplain.xml_to_obj(
    f, strip_space=True, process_content=postprocessor)

assert my_dict == {'example': [{'str': 'baguette'}, {'int': 1}]}
```
