### ISSUE TITLE
assert error in convert from yaml to xml 

### ISSUE THREAD

**Issue by morawi** [guillon/xmlplain#2]
Hi, I am trying to convert from yaml to xml but I am getting this error, any idea how to find the source of error?

```
  File "...\lib\site-packages\xmlplain.py", line 523, in generate_from
    assert(len(root.items()) == 1)

AssertionError

```

This is the function I am using:

```
import xmlplain


def yaml_to_xml(yaml_fname, xml_fname):
    # Read the YAML file
    with open(yaml_fname) as inf:
        root = xmlplain.obj_from_yaml(inf)

    # Output back XML
    with open(xml_fname, "w") as outf:
        xmlplain.xml_from_obj(root, outf, pretty=True, indent='    ',)
        
```
In my case, the root has 13 items, so I am not sure what is wrong here.

**Comment by munael** [comment]
XML can has only one root element. Scope your current map under a new root.

**Comment by autonomobil** [comment]
How to do that nicely? Can't change the yaml-file

**Comment by guillon** [comment]
Hi,
actually xmlplain is not suited for converting arbitrary yaml to xml.
The intent of this library is the reverse: converting an arbitrary xml document to a yaml representation, and then optionally converting this yaml representation or a conformant one back to xml.
The yaml representation used is not arbitrary and there are constraints on its topology such that it can be converted back to xml.

Hence to summarize, if your use case is to convert arbitrary yaml to xml, it is not the rigth tool. Sorry for this.
